name: myhuntmigration
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  camera: ^0.10.3+2
  curved_navigation_bar: ^1.0.3
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^2.0.4
  google_fonts: ^4.0.3
  path: ^1.8.2
  path_provider: ^2.0.14
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/hack2impactsamplefeed/
    - assets/Icons/
  
    
    

